# GoReleaser configuration for dart-statistic-scraper
project_name: dart-scraper

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/dart-scraper/main.go
    binary: dart-scraper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  disable: false
  draft: false
  prerelease: auto
  name_template: "Release {{.Tag}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'